name: fashionflow
version: "1.0.0"
config-version: 2

profile: fashionflow

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fashionflow:
    staging:
      +schema: staging
      +materialized: view
      +tags: ["staging"]
    marts:
      +schema: mart
      +materialized: table
      +tags: ["mart"]

vars:
  source_database: "de-project-502311"
  source_schema: "fashionflow_raw"
